### ISSUE TITLE
Vulcan scale incorrect

### ISSUE THREAD

**Issue by JacobB094** [nolifejordan/Kiwi-Orbital-Designs-Systems#8]
![screenshot391](https://github.com/user-attachments/assets/dd0af9e8-2fae-4ce3-b056-2edde0cdf44d)
Vulcan parts appear to be some weird size between 3.75m and 3.125m. The tankage is supposed to be using Delta IV tooling, so I suspect they were supposed to be 3.125m Note that just taking real size and multiplying by 0.64 gives 3.2m, not 3.125m, which is likely what happened here.

**Comment by nolifejordan** [comment]
the vulcan scale isnt incorrect as it is meant to be wider than delta iv 
the 3.5m diameter was chosen as it was the same diameter as the atlas v fairing which is the same as vulcan's diameter (5.4m irl)
scaling is actually .625 or 5/8 and is rounded to the nearest standard part size
